-- Two-factor authentication (TOTP), one-time recovery codes and trusted
-- devices are deliberately kept in their own tables: they are security
-- credentials with a different lifecycle from the user profile row.
CREATE TABLE pr_user_two_factor (
    user_id BIGINT PRIMARY KEY REFERENCES pr_users(id) ON DELETE CASCADE,
    -- Base32 encoded shared secret (RFC 4648 alphabet, no padding).
    secret VARCHAR(64) NOT NULL,
    -- False while the user is still in the scan-and-confirm step, so an
    -- abandoned setup never locks the account.
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE pr_user_recovery_codes (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES pr_users(id) ON DELETE CASCADE,
    -- Recovery codes are stored hashed; the plaintext is shown exactly once.
    code_hash VARCHAR(100) NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_recovery_codes_user ON pr_user_recovery_codes(user_id, created_at DESC);

CREATE TABLE pr_user_devices (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES pr_users(id) ON DELETE CASCADE,
    -- Stable identifier generated by the client and kept in its own storage.
    device_key VARCHAR(64) NOT NULL,
    device_name VARCHAR(120) NOT NULL,
    user_agent VARCHAR(500),
    ip_address VARCHAR(64),
    -- A trusted device may skip the second factor at the next sign-in.
    trusted BOOLEAN NOT NULL DEFAULT FALSE,
    trusted_until TIMESTAMP WITH TIME ZONE,
    last_login_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_user_devices_key ON pr_user_devices(user_id, device_key);
CREATE INDEX idx_user_devices_user ON pr_user_devices(user_id, last_login_at DESC);
