package org.paperreader.controller

import io.mockk.every
import io.mockk.mockk
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.ObjectProvider
import org.springframework.boot.info.BuildProperties
import java.util.Properties

class HealthControllerTest {

    @Test
    fun `reports the version generated by the current build`() {
        val buildProperties = BuildProperties(
            Properties().apply { setProperty("version", "0.1.19-fix") },
        )
        val provider = mockk<ObjectProvider<BuildProperties>>()
        every { provider.getIfAvailable() } returns buildProperties

        val response = HealthController(provider).health()

        assertEquals("ok", response.data?.get("status"))
        assertEquals("0.1.19-fix", response.data?.get("version"))
    }

    @Test
    fun `uses a clear development fallback when build metadata is unavailable`() {
        val provider = mockk<ObjectProvider<BuildProperties>>()
        every { provider.getIfAvailable() } returns null

        val response = HealthController(provider).health()

        assertEquals("development", response.data?.get("version"))
    }
}
